### ISSUE TITLE
 Error(s) in loading state_dict for DataParallel

### ISSUE THREAD

**Issue by aaaaalun** [megvii-research/RealFlow#11]
Hi,i meet this problem and how to solve it?
--------------------------------------------------------------------------------
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Missing key(s) in state_dict: "module.fnet.conv1.weight"
---------------------------------------------------------------------------------
use demo.py

**Comment by Timer-x** [comment]
modify line 118 may help you
```
model = RAFT(args) 
```

**Comment by aaaaalun** [comment]
thank!
i have solved it, but i have a new error
-------------------------------------------
raise exception
TypeError: Caught TypeError in replica 1 on device 1.
TypeError: forward() missing 2 required positional arguments: 'image1' and 'image2'
-------------------------------------------
i think the problem is i have two gpu.

**Comment by aaaaalun** [comment]
> ## thank!
> i have solved it, but i have a new error
> ## raise exception
> TypeError: Caught TypeError in replica 1 on device 1.
> TypeError: forward() missing 2 required positional arguments: 'image1' and 'image2'
> i think the problem is i have two gpu.

modify " model = torch.nn.DataParallel(RAFT(args),device_ids=[0])"

**Comment by aaaaalun** [comment]
> ## thank!
> i have solved it, but i have a new error
> ## raise exception
> TypeError: Caught TypeError in replica 1 on device 1.
> TypeError: forward() missing 2 required positional arguments: 'image1' and 'image2'
> i think the problem is i have two gpu.

i solve it by myself! 
modify " model = torch.nn.DataParallel(RAFT(args),device_ids=[0])"

**Comment by aaaaalun** [comment]
so many errors.................
---------------------------------------------------------------
File "D:\work\github\RealFlow-main\RealFlow-main\softmax_splatting\softsplat.py", line 416, in FunctionSoftsplat
    assert(strType in ['summation', 'average', 'linear', 'softmax', 'gumbel_softmax', 'max'])
AssertionError
---------------------------------------------------------------
i have finished my program,but i can not get the results.

**Comment by aaaaalun** [comment]
> ## so many errors.................
> ## File "D:\work\github\RealFlow-main\RealFlow-main\softmax_splatting\softsplat.py", line 416, in FunctionSoftsplat
> assert(strType in ['summation', 'average', 'linear', 'softmax', 'gumbel_softmax', 'max'])
> AssertionError
> i have finished my program,but i can not get the results.

hhh,i solve it.
python demo.py --model xx --save_path xx--iter xx --splatting max

**Comment by aaaaalun** [comment]
thanks for share!
