### ISSUE TITLE
attributeerror: 'nonetype' object has no attribute 'seek'.

### ISSUE THREAD

**Issue by wq247726404** [megvii-research/RealFlow#15]
请问一下这个报错是什么意思呢？

**Comment by coolbeam** [comment]
Could you please provide more specific error information regarding this issue? I'm not sure how to address it at the moment.

**Comment by wq247726404** [comment]
Thank you very much for your reply！
    I later found out the cause and fixed it.I will contact you if there are any more questions in the future.
Thank you again for your reply!




羙、德菗潒↘
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "megvii-research/RealFlow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月13日(星期六) 晚上6:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [megvii-research/RealFlow] attributeerror: 'nonetype' object has no attribute 'seek'. (Issue #15)





 
Could you please provide more specific error information regarding this issue? I'm not sure how to address it at the moment.

**Comment by wq247726404** [comment]
OK



---Original---
From: "kunming ***@***.***&gt;
Date: Sat, May 13, 2023 19:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [megvii-research/RealFlow] attributeerror: 'nonetype' object hasno attribute 'seek'. (Issue #15)




 
Closed #15 as completed.

**Comment by GavinHao-RS** [comment]
hello wq247726404, I have the same problem today, could you tell me how to solve it?
