### ISSUE TITLE
 resource not found

### ISSUE THREAD

**Issue by GavinHao-RS** [megvii-research/RealFlow#17]
There is a 

```python
depth_model_path = "DPT/model/dpt_large-midas-2f21e586.pt"
```

in both demo.py and RealFLow.py, but I can't find the .pt file under this path, I wonder could you please provide this file?

**Comment by coolbeam** [comment]
Hi, please refer to the README.md, or you can download it from: https://github.com/intel-isl/DPT/releases/download/1_0/dpt_large-midas-2f21e586.pt
