### ISSUE TITLE
How many iterations of GRU used in RAFT forward operation of raft-RFAB.pth pretrained model ?

### ISSUE THREAD

**Issue by ducheng678** [megvii-research/RealFlow#2]
I just notice that you set iterations when kitti to 24 and sintel to 32, but have no idea about your RAFT model setting trained by RF-AB dataset.

**Comment by DuCheng2018** [comment]
I just notice that you set iterations as kitti to 24 and sintel to 32, but have no idea about your model setting trained by RF-AB dataset.

**Comment by coolbeam** [comment]
Hi, RAFT model setting trained by RF-AB dataset is the same: 12 when training, 24 when testing on kitti and 32 when testing on sintel. Thank you.

**Comment by coolbeam** [comment]
> I just notice that you set iterations when kitti to 24 and sintel to 32, but have no idea about your RAFT model setting trained by RF-AB dataset.

Hi, RAFT model setting trained by RF-AB dataset is the same: 12 when training, 24 when testing on kitti and 32 when testing on sintel. Thank you.

**Comment by ducheng678** [comment]
> > I just notice that you set iterations when kitti to 24 and sintel to 32, but have no idea about your RAFT model setting trained by RF-AB dataset.
> 
> Hi, RAFT model setting trained by RF-AB dataset is the same: 12 when training, 24 when testing on kitti and 32 when testing on sintel. Thank you.

Get it. Thanks a lot
