### ISSUE TITLE
Which data augmentation is applied to train RAFT on RF-Ktrain?

### ISSUE THREAD

**Issue by Byungki-Kwon** [megvii-research/RealFlow#4]
Thanks for releasing the data generation code of excellent work.

I wonder the range of data augmentation to train RAFT on RF-Ktrain, such that 1) crop_size 2) min_scale 3) max_scale 4) do_flip, which are included RAFT/core/dataset.py file.

**Comment by coolbeam** [comment]
Thank you. We use the official code of RAFT without any modification to train RAFT on our generated datasets. Therefore, the range of data augmentation for training RAFT on RF-Ktrain is the same as that included in RAFT/core/dataset.py file.
