### ISSUE TITLE
Pretrained RAFT checkpoints

### ISSUE THREAD

**Issue by Sharpiless** [megvii-research/RealFlow#6]
Wonderful work! But where to download the pretrained  C+T model? We only find C and T.

**Comment by coolbeam** [comment]
> 

Hi, C+T model means that the network is first trianed on C and then finetuned on T. The model RAFT-things is finetuned on T using parameters of RAFT-C. So pretrained C+T model is RAFT-T. Thank you for pointing this out. We will make this clear in the README file.

**Comment by Sharpiless** [comment]
Got it. Thanks!
