### ISSUE TITLE
About factor alpha

### ISSUE THREAD

**Issue by tobylyf** [megvii-research/RealFlow#7]
Thanks for your great work.
I have a question about the factor alpha. Essentially, the Bi-directional Hole Filling method is based on both the forward and backward flow, where the two flow are "reversed". But when alpha is greater than 1, the destination time t would be after I2 too, so both flow would be forward. In this case, there should be hole area that I2 also can't cover. How to deal with this problem when you sample alpha from [0, 2]?

**Comment by coolbeam** [comment]
> 

Thanks for pointing out this problem. In our experiments, we did not deal with this situation specifically. Dealing with this problem may be a plan for further improvement.

**Comment by tobylyf** [comment]
Alright. Thanks!
